stages:
  - build
  - test

variabled:
  PRESET: "clang-debug-dev"
  
build-job:
  stage: build
  script:
    - cmake --preset $PRESET
    - cmake --build build/$PRESET
  artifacts:
    paths:
      - build/$PRESET

test-job:
  stage: test
  dependencies:
    - build-job
  script:
    - ctest --preset test-$PRESET
