stages:
  - build
  - test
  - coverage
  
variables:
  PRESET: "clang-debug-dev"
  BUILD_DIR: "build/clang-debug-dev"
  TEST_DIR: "build/clang-debug-dev/tests"
  
build-job:
  stage: build
  script:
    - cmake --preset $PRESET
    - cmake --build $BUILD_DIR
  artifacts:
    paths:
      - $BUILD_DIR

test-job:
  stage: test
  dependencies:
    - build-job
  script:
    - LLVM_PROFILE_FILE="coverage-%p.profraw"
    - ctest --test-dir $TEST_DIR
    
coverage-job:
  stage: coverage
  dependencies:
    - test-job
  script:
    - scrpits/coverage.sh $TEST_DIR
  artifacts:
    paths:
      - $TEST_DIR/coverage-html
