stages:
  - build
  - test
  
build-job:
  stage: build
  script:
    - cmake --preset clang-debug-dev
    - cmake --build build/clang-debug-dev
  artifacts:
    paths:
      - build/clang-debug-dev

test-job:
  stage: test
  dependencies:
    - build-job
  script:
    - ctest --test-dir build/clang-debug-dev